include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
  errors:
    always_use_package_imports: ignore
    invalid_annotation_target: ignore
    comment_references: ignore
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_void_async: false
    one_member_abstracts: false
    constant_identifier_names: false
    provide_deprecation_message: false
    prefer_mixin: false
    sort_pub_dependencies: false
    avoid_catches_without_on_clauses: false
    join_return_with_assignment: false
    prefer_expression_function_bodies: false
    avoid_js_rounded_ints: false

dart_code_metrics:
  extends:
    - package:surf_dcm_presets/all.yaml