name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.8.4
topics:
  - error
  - errors
  - logs
  - devtools
  - tool

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.3
  device_info_plus: ^10.0.1
  device_info_plus_platform_interface: ^7.0.0
  package_info_plus: ^8.0.1
  dio: ^5.3.3
  logging: ^1.0.2
  universal_io: ^2.0.4

dev_dependencies:
  surf_lint_rules: ^3.1.0
  surf_dcm_presets: ^0.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
